---
title: "Lab 2: Exploration by visualization: the streaming movies dataset"
author: "MinJae Jo"
date: "`2025-09-12"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    highlight: tango
    toc: false
    df_print: kable
    fig_caption: no
    number_sections: no
    dev: pdf
---

```{r setup, include = FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# Set knitr options
knitr::opts_chunk$set(
  echo = TRUE, eval = TRUE, fig.width = 5,
  fig.asp = 0.618, out.width = "80%", dpi = 120,
  fig.align = "center", cache = FALSE
)

# Load packages
suppressPackageStartupMessages(library(tidyverse))

# Load dataset
streaming <- read_csv("streaming.csv")
```

* * *

## Visualization by example

### Exercise 1
```{r}
library(ggplot2)
qplot(x = im_db, binwidth = 0.5, data = streaming)
```



### Exercise 2
```{r}
library(ggplot2)

qplot(
  x = im_db,
  binwidth = 0.5,
  fill = main_language,
  data = streaming
)
```



### Exercise 3

Foreign films look slightly higher on average, which is a natural phenomenon as only popular or well-received films are usually streamed.


### Exercise 4
```{r}
library(ggplot2)

qplot(
  x = im_db,
  binwidth = 0.5,
  facets = ~ age,
  data = streaming
)
```


### Exercise 5
```{r}
library(ggplot2)

qplot(
  x = rotten_tomatoes,
  y = im_db,
  data = streaming
)
```


### Exercise 6





### Exercise 7





### Exercise 8

  


### Exercise 9