---
title: "Lab 11"
author: "MinJae Jo"
date: "`r Sys.Date()`"
output: flexdashboard::flex_dashboard
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(plotly)
library(crosstalk)

pokemon <- read_csv("pokemon.csv")
shared_pokemon <- SharedData$new(pokemon)

```

Column
-------------------------------------

### Boxplot of Total Stats by Pokemon Type


```{r, echo=FALSE}
ordered_types <- pokemon %>%
  mutate(`Type 1` = reorder(`Type 1`, Total, FUN = median)) %>%
  pull(`Type 1`) %>%
  levels()

p1 <- ggplot(shared_pokemon, aes(x = `Type 1`, y = Total, fill = `Type 1`)) +
  geom_boxplot() +
  scale_x_discrete(limits = ordered_types) +
  labs(x = "Pokemon Type") +
  theme(axis.text.x = element_text(angle = 45))

ggplotly(p1)

```

Column
-------------------------------------

### Scatterplot of Attack vs Defense


```{r, echo=FALSE}
p <- ggplot(pokemon, aes(x = Defense, y = Attack, color = `Type 1`)) +
  geom_point()

ggplotly(p)

```

Sidebar {.sidebar}
-------------------------------------
```{r}
library(tidyverse)
library(plotly)
library(crosstalk)

pokemon <- read_csv("pokemon.csv")
```