---
title: "Lab 4: Tidying your dataset"
author: "MinJae Jo"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    highlight: tango
    toc: false
    df_print: kable
    fig_caption: no
    number_sections: no
    dev: pdf
  html_document:
    highlight: tango
    self_contained: true
    theme: paper
    toc: no
    df_print: kable
    fig_caption: no
    number_sections: no
    smart: yes
    dev: svg
  github_document:
    html_preview: false
    toc: true
    toc_depth: 4
    dev: svg
    df_print: kable
---

```{r setup, include = FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# Set knitr options
knitr::opts_chunk$set(
  echo = TRUE, eval = TRUE, fig.width = 5,
  fig.asp = 0.618, out.width = "80%", dpi = 120,
  fig.align = "center", cache = FALSE
)

# Load packages
suppressPackageStartupMessages(library(tidyverse))

# Load dataset
brauer <- read_rds("brauer2008.rds")
```

---

## Prune the dataset

### Exercise 1
```{r}
brauer2 <- brauer %>%
  select(-GID, -YORF, -GWEIGHT)
```


## Enforcing one observation per row

### Exercise 2
```{r}
library(tidyr)

brauer3 <- brauer2 %>%
  pivot_longer(
    cols = `G0.05`:`U0.3`,
    names_to  = "sample",
    values_to = "expression",
    values_drop_na = TRUE
  )
```


## Enforcing one column per variable and one value per cell

### Exercise 3

```{r}
library(tidyr)

brauer4 <- brauer3 %>%
  separate(sample, into = c("nutrient", "rate"), sep = 1, convert = TRUE) %>%
  separate(NAME,
           into = c("gene_name", "biological_process", "molecular_function", "systematic_id", "number"),
           sep = "\\|\\|")

```

### Exercise 4

```{r}
library(tidyr)
library(stringr)

brauer5 <- brauer3 %>%
  separate(
    NAME,
    into = c("gene_name","biological_process","molecular_function","systematic_id","number"),
    sep  = "\\|\\|",
    fill = "right",
    extra = "merge"       
  ) %>%
  mutate(
    across(c(gene_name, biological_process, molecular_function, systematic_id, number),
           str_trim)
  )

```


### Exercise 5
```{r}
library(stringr)

brauer_tidy <- brauer5 %>%
  mutate_at(vars(gene_name:number), str_trim)
```


## Visualizations using the tidy dataset

### Exercise 6
