---
title: "Lab 9: APIs"
author: "MinJae Jo"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    highlight: tango
    toc: false
    df_print: kable
    fig_caption: no
    number_sections: no
    dev: pdf
  html_document:
    highlight: tango
    self_contained: true
    theme: paper
    toc: no
    df_print: kable
    fig_caption: no
    number_sections: no
    smart: yes
    dev: svg
  github_document:
    html_preview: false
    toc: true
    toc_depth: 4
    dev: svg
    df_print: kable
geometry: margin=1in
fontsize: 11pt
documentclass: article
---

```{r setup, include = FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# Set knitr options
knitr::opts_chunk$set(echo = TRUE)
# Load required packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(tidycensus))
options(tigris_use_cache = TRUE)
```

* * *

## Lab report

## Exercises

#### Exercise 1
```{r, echo=FALSE}
library(tidycensus)
va_pop_2010 <- get_decennial(
  geography = "county",
  state = "VA",
  variables = c("P001001"),
  year = 2010,
  show_call = TRUE,
  geometry = TRUE
)
```
#### Exercise 2
```{r, echo=FALSE}
library(dplyr)
library(ggplot2)

va_pop_2010 %>%
  ggplot(aes(fill = value)) +
  geom_sf() +
  scale_fill_viridis_c(option = "magma")
```


#### Exercise 3
```{r, echo=FALSE}
va_tracts_2010 <- get_decennial(
  geography = "tract",
  state = "VA",
  variables = c(
    "P001001",  # total population
    "P003002",  # white population
    "H001001",  # total number of housing units
    "H004002",  # housing units with mortgages
    "H004003"   # housing units owned fully (no mortgage)
  ),
  year = 2010
)
```
#### Exercise 4
```{r}
library(tidyr)

va_tracts_wide <- va_tracts_2010 %>%
  pivot_wider(
    names_from = variable,
    values_from = value
  )
```
#### Exercise 5
```{r}
library(dplyr)

va_tracts_final <- va_tracts_wide %>%
  mutate(
    pct_nonwhite = ((P001001 - P003002) / P001001) * 100,
    pct_owned = ((H004002 + H004003) / H001001) * 100
  )
```
#### Exercise 6
```{r, echo=FALSE}
library(ggplot2)
library(tidyr)

va_tracts_final %>%
  pivot_longer(cols = c(pct_nonwhite, pct_owned),
               names_to = "metric", values_to = "value") %>%
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30) +
  facet_wrap(~ metric, scales = "free_x") +
  labs(x = "Percent", y = "Count", title = "Distributions of New Percentage Columns")

ggplot(va_tracts_final, aes(y = pct_nonwhite)) + geom_boxplot() +
  labs(y = "Percent Non-White", title = "Distribution: pct_nonwhite")

ggplot(va_tracts_final, aes(y = pct_owned)) + geom_boxplot() +
  labs(y = "Percent Owner-Occupied", title = "Distribution: pct_owned")
```
#### Exercise 7
```{r, echo=FALSE}
library(ggplot2)

ggplot(va_tracts_final, aes(x = pct_nonwhite, y = pct_owned)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  labs(
    x = "Percent Non-White",
    y = "Percent Owner-Occupied Homes",
    title = "Relationship between Racial Composition and Home Ownership in Virginia (2010)"
  ) +
  theme_minimal()
```
