---
title: "Lab 5: Data cleaning"
author: "Fill in your full name"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    highlight: tango
    dev: pdf
---

```{r setup, include = FALSE}
# DO NOT ALTER THIS CHUNK
# Set knitr options
knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  cache = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.width = 5,
  fig.asp = 0.618,
  fig.align = "center",
  out.width = "80%",
  dpi = 120
)
# Load required packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(lubridate))
# Load dataset
towed <- read_rds("towed_vehicles.rds")
```

## Exercises

### Exercise 1
```{r, echo=FALSE, message=FALSE, warning=FALSE}
towed_renamed <- towed %>%
  rename(
    tow_date          = `Tow Date`,
    make              = Make,
    style             = Style,
    model             = Model,
    color             = Color,
    plate             = Plate,
    state             = State,
    towed_to_address  = `Towed to Address`,
    tow_facility_phone= `Tow Facility Phone`,
    inventory_number  = `Inventory Number`
  )

colnames(towed_renamed)
```


### Exercise 2

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(lubridate)

towed_renamed_2 <- towed_renamed %>%
  mutate(tow_date = mdy(tow_date))
str(towed_renamed_2)
class(towed_renamed_2$tow_date)
```



### Exercise 3
```{r, echo=FALSE, message=FALSE, warning=FALSE}
tow_make_count <- towed_renamed_2 %>%
  count(make)

nrow(tow_make_count)

tow_make_count %>% 
  filter(n == 1)
```


### Exercise 4
```{r}
tow_make_count_1 <- tow_make_count %>%
  slice(1:20)

tow_make_count_2 <- tow_make_count %>%
  slice(21:40)

tow_make_count_3 <- tow_make_count %>%
  slice(41:60)

tow_make_count_4 <- tow_make_count %>%
  slice(61:80)
```


### Exercise 5
```{r}
towed_clean <- towed_renamed_2 %>%
  mutate(
    make = recode(
      make,
      DODD = "DODG",
      CHEVV = "CHEV", 
      TOYTA = "TOYT"
    )
  )

```

### Exercise 6
```{r}
towed_partial_clean <- towed_renamed_2 %>%
  mutate(
    make = recode(
      make,
      DODD = "DODG",
      BUCI = "BUIC"
    )
  )
```

### Exercise 7
```{r}
towed_partial_clean <- towed_partial_clean %>%
  mutate(
    make = recode(
      make,
      JAG = "JAGU"
    )
  )

```

### Exercise 8
```{r}
towed_make_clean <- towed_partial_clean %>%
  mutate(
    make = recode(
      make,
      "DODD" = "DODG",   # Dodge
      "D0DD" = "DODG",   # sometimes a zero sneaks in
      "BUCI" = "BUIC",   # Buick
      "JAG"  = "JAGU"    # Jaguar (per VTR-249.pdf)
    )
  )
```


## Additional questions

### Question 1




### Question 2


