---
title: "Lab 6: Saving for Retirement"
author: "Fill in your full name"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    highlight: tango
    toc: false
    df_print: kable
    fig_caption: no
    number_sections: no
    dev: pdf
  html_document:
    highlight: tango
    self_contained: true
    theme: paper
    toc: no
    df_print: kable
    fig_caption: no
    number_sections: no
    smart: yes
    dev: svg
  github_document:
    html_preview: false
    toc: true
    toc_depth: 4
    dev: svg
    df_print: kable
---

```{r setup, include = FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# Set knitr options
knitr::opts_chunk$set(
  echo = TRUE, eval = TRUE, fig.width = 5,
  fig.asp = 0.618, out.width = "80%", dpi = 120,
  fig.align = "center", cache = FALSE
)
```

---

## Exercise 1

```{r}
savings <- 0
income <- 58000
interest_rate <- 0.06
savings_rate <- 0.10

for (year in 22:65) {
  savings <- savings + (income * savings_rate) + (savings * interest_rate)
}

savings
```




## Exercise 2
```{r}
final_savings <- 1158597
annual_withdrawal <- final_savings * 0.04
annual_withdrawal
```


## Exercise 3
```{r}
savings <- 0
income <- 58000
interest_rate <- 0.06
savings_rate <- 0.10
employer_match <- 0.05

for(year in 22:65){
  savings <- savings + (income * (savings_rate + employer_match)) + (savings * interest_rate)
}

savings
```

## Exercise 4
```{r}
savings <- 0
income <- 58000
interest_rate <- 0.06
savings_rate <- 0.10
employer_match <- 0.05

for(year in 22:65){
  savings <- savings + (income * (savings_rate + employer_match)) + (savings * interest_rate)
  income <- income + 1000
}

savings
```

## Exercise 5



