---
title: "Lab 5: Birth Ratios"
author: "Fill in your full name"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    highlight: tango
    toc: false
    df_print: kable
    fig_caption: no
    number_sections: no
    dev: pdf
  html_document:
    highlight: tango
    self_contained: true
    theme: paper
    toc: no
    df_print: kable
    fig_caption: no
    number_sections: no
    smart: yes
    dev: svg
  github_document:
    html_preview: false
    toc: true
    toc_depth: 4
    dev: svg
    df_print: kable
---

```{r setup, include = FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# Set knitr options
knitr::opts_chunk$set(
  echo = TRUE, eval = TRUE, fig.width = 5,
  fig.asp = 0.618, out.width = "80%", dpi = 120,
  fig.align = "center", cache = FALSE
)
# Load packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(infer))
suppressPackageStartupMessages(library(HistData))
set.seed(42)
```

---

## Visualizing and quantifying the distribution

### Exercise 1




### Exercise 2
```{r, echo=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(HistData)

data("Arbuthnot")

Arbuthnot_clean <- Arbuthnot |> distinct(Year, .keep_all = TRUE) |>
  mutate(Ratio = Males / Females)
ggplot(data = Arbuthnot_clean) +
  geom_boxplot(aes(x = "", y = Ratio)) +
  coord_flip() +
  labs(title = "Arbuthnot birth ratio (Males/Females): Boxplot",
       x = NULL, y = "Ratio")
ggplot(data = Arbuthnot_clean, aes(x = Ratio, y = ..density..)) +
  geom_histogram(binwidth = 0.01, color = "white") +
  labs(title = "Arbuthnot birth ratio (Males/Females): PMF",
       x = "Ratio", y = "Probability density")
```


### Exercise 3

```{r, echo=FALSE, warning=FALSE}
ggplot(data = Arbuthnot_clean, aes(x = Ratio, y = after_stat(density))) +
geom_histogram(binwidth = 0.01, fill = "lightblue", color = "white", alpha = 0.6) +
geom_density(color = "red", linewidth = 1) +
labs(
title = "Arbuthnot birth ratio (Males/Females): PMF + Density",
x = "Ratio",
y = "Probability density"
)

```

### Exercise 4
```{r, echo=FALSE, warning=FALSE}
Arbuthnot_clean %>%
summarize(
mean = mean(Ratio),
median = median(Ratio),
sd = sd(Ratio),
iqr = IQR(Ratio),
min = min(Ratio),
max = max(Ratio)
)

```

## `infer`ing a trend

### Exercise 5




### Exercise 6